// SPDX-FileCopyrightText: 2021 Lightmeter <hello@lightmeter.io>
// SPDX-FileCopyrightText: 2021 Lightmeter <hello@lightmeter.io>
//
// SPDX-License-Identifier: AGPL-3.0-only

package collector

import (
	"database/sql"

	"gitlab.com/lightmeter/controlcenter/lmsqlite3/migrator"
	"gitlab.com/lightmeter/controlcenter/util/errorutil"
)

func init() {
	migrator.AddMigration("intel-collector", "8_remove_invalid_events.go", func(tx *sql.Tx) error {
		// Remove lots of useless events generated by bug #693
		// It's important to notice that the disk space is not reclaimed until
		// a vacuum is executed!
		sql := `
delete from events where content_type = '';
`

		_, err := tx.Exec(sql)
		if err != nil {
			return errorutil.Wrap(err)
		}

		return nil
	}, func(*sql.Tx) error { return nil })
}
