// SPDX-FileCopyrightText: 2021 Lightmeter <hello@lightmeter.io>
//
// SPDX-License-Identifier: AGPL-3.0-only

//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"gitlab.com/lightmeter/controlcenter/util/errorutil"
	"io/ioutil"
	"os"
	"strings"
)

func escapeBackticks(s string) string {
	return strings.ReplaceAll(s, "`", "` + \"`\" + `")
}

func main() {
	origContent, err := ioutil.ReadFile("templates/template.thtml")
	errorutil.MustSucceed(err)

	f, err := os.Create("template.gen.go")
	errorutil.MustSucceed(err)

	_, err = fmt.Fprintf(f, `// Code generated by running "go generate". DO NOT EDIT
// +build release dev

//nolint
package email

func init() {
	messageTemplate = %s%s%s
}`, "`", escapeBackticks(string(origContent)), "`")

	errorutil.MustSucceed(err)
}
