#!/bin/bash

# Script to remove identifying information from standard mail log files generated by Postfix
# 
# Note: Requires the additional script `log_cleaner.py` to be located within the same path
# Usage: batch_log_cleaner /path/to/source/log/dir /path/to/destination/log/dir
#        e.g.  batch_log_cleaner /var/mail/log /home/admin/cleaned_logs

set -e
set -o pipefail

UTILS_DIR="$(dirname $(realpath "$0"))"

SRCDIR="$(realpath "$1")"
DESTDIR="$(realpath "$2")"

[ -n "$SRCDIR" ]
[ -d "$SRCDIR" ]

[ -n "$DESTDIR" ]

find "$SRCDIR" -name 'mail.log.*' | while read FILEPATH; do
  echo "Cleaning $FILEPATH"
  FILE="$DESTDIR/${FILEPATH##${SRCDIR}}"
  mkdir -p "$(dirname "$FILE")"
  "${UTILS_DIR}/log_cleaner.py" < "$FILEPATH" > "$FILE"
done
